// <auto-generated />
using GraphQLImplemention.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLImplemention.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQLImplemention.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roll")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ahmed",
                            Roll = "1001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mohamed",
                            Roll = "1002"
                        },
                        new
                        {
                            Id = 3,
                            Name = "amer",
                            Roll = "1003"
                        },
                        new
                        {
                            Id = 4,
                            Name = "hazeem",
                            Roll = "1004"
                        },
                        new
                        {
                            Id = 5,
                            Name = "hamza",
                            Roll = "1005"
                        },
                        new
                        {
                            Id = 6,
                            Name = "hassan",
                            Roll = "1006"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ebrahim",
                            Roll = "1007"
                        },
                        new
                        {
                            Id = 8,
                            Name = "moataz",
                            Roll = "1008"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
